name: Java CI with Maven
on:
  push:
    branches: [ "main", "dev", "prod-support" ]
  pull_request:
    branches: [ "main", "dev", "prod-support" ]
jobs:
  build:
    name: Application Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: List directory contents
        run: ls -la
      - name: Build with Maven
        run: mvn -B clean package
      - name: Run Tests
        run: mvn test -X
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root